#!/bin/bash
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# 
# TEMPLATE script to start a build. This is run inside a container
#
# 6 July 2016 -- Jeremy.Mordkoff@riftio.com -- adapted from the riftware version
# 

HERE=$(realpath $(dirname $0))
OSM_JENKINS=$(dirname $HERE)
. $OSM_JENKINS/common/all_funcs

# SET YOU MDG repository name here
export OSM_MDG=SO
# @vasgl: export proxy settings
export http_proxy=http://icache.intranet.gr:80
export https_proxy=http://icache.intranet.gr:80
export no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,*.local

OSM_load_config
OSM_git_checkout "$@"

# @vasgl: Install and configure npm preemptively
apt install npm -y
npm set strict-ssl false
npm config set registry http://registry.npmjs.org/
npm config set proxy http://icache.intranet.gr:80
npm config set https-proxy http://icache.intranet.gr:80

trap 'WARNING "INTERRUPT"; exit 1' INT

INFO "starting build"
make clean || FATAL "make clean failed"
# @vasgl: preserve the environment
sudo -E ./BUILD.sh

RC=$?

INFO "done, RC=$RC"
exit $RC


